Update styling for long dropdown options
stamen/maperture pull request #163
Opened 2023-04-03 19:07 UTC by aparlato

## Description

Updates styling of dropdown preset options with long names to:
- max out at 90% width
- truncate text beyond that

Closes #79

## QA steps

- [ ] Update code or config to make a preset have a _very_ long name
- [ ] Try all different view modes
- [ ] Confirm that styling is appropriate

## Author checklist

### Create the PR

- [x] Fill out PR template
- [x] Make sure you've added a CHANGELOG entry under "Unreleased"
- [x] Request a review
- [ ] Make any requested changes and get approval

### After approval

- [ ] Merge any changes from `main` into your branch, resolve any conflicts
- [ ] Squash & merge changes into `main`
- [ ] Delete branch

2023-04-03 20:35 UTC, ebrelsford requested changes
I think we have an errant style file in here we want to remove!

Otherwise this is a big improvement.

2023-04-03 20:35 UTC, ebrelsford commented on public/style.json
I don't think we want to include this, right?

2023-04-03 22:16 UTC, aparlato commented on public/style.json
Yikes! I'm not sure how that happened 😬 Must have been working on something separate here and let untracked changes make their way into this branch.

2023-04-04 12:48 UTC, ebrelsford approved these changes

2023-04-04 13:51 UTC, merged