Multiple level dropdowns
stamen/maperture pull request #194
Opened 2024-07-09 21:47 UTC by aparlato

## Description

This PR enables style presets to have a second nested level to help organize long lists of styles. We do not allow more than two levels of nesting.

### TODO
- [ ] Apply same treatment to branch options
- [ ] Add documentation of syntax

Closes #193

## QA steps

- [ ] Confirm that selecting a nested style works as expected
- [ ] Confirm on refresh that the dropdown finds the nested style
- [ ] Confirm all dropdowns work (switched all to the `sveltestrap` library for consistency)

## Author checklist

### Create the PR

- [ ] Fill out PR template
- [ ] Make sure you've added a CHANGELOG entry under "Unreleased"
- [ ] Request a review
- [ ] Make any requested changes and get approval

### After approval

- [ ] Merge any changes from `main` into your branch, resolve any conflicts
- [ ] Squash & merge changes into `main`
- [ ] Delete branch

2024-07-10 19:35 UTC, ebrelsford requested changes
Looks great and useful!

Any chance we can handle this horizontal overflow?

![image](https://github.com/stamen/maperture/assets/375002/7ff4f833-5541-4d91-ba19-bb94fef2a0b0)

Otherwise lgtm.

2024-07-16 20:24 UTC, aparlato commented
@ebrelsford I've got the list items to truncate and made labels not go over their container (and also adjusted whether it's a drop-down or drop-up based on screen position) but I'm having trouble getting the toggle itself to use truncation due to how its implemented in the library.

It's basically a div with an `::after` property for the triangle so the ellipsis doesn't work as I expect. Any suggestion here or should we just move forward with it as-is:
<img width="665" alt="image" src="https://github.com/user-attachments/assets/640fddae-ec97-463a-b71f-b0d9d659075d">

2024-07-22 15:08 UTC, aparlato commented
@ebrelsford nevermind the above, I figured out how to make the ellipsis work correctly here!

2024-07-23 15:30 UTC, ebrelsford approved these changes

2024-07-23 15:30 UTC, merged