change map orientation
stamen/maperture pull request #95
Opened 2022-09-06 15:37 UTC by aparlato

Closes https://github.com/stamen/maperture/issues/94

This PR changes the orientation of maps in the mirror layout to use a column approach with exceptions at 2 and 6 maps to keep maps either square or in portrait orientation (as opposed to landscape).

### QA
- [ ] In mirror layout, confirm any number of maps looks good and tends toward a portrait layout

2022-09-06 15:41 UTC, aparlato commented on src/components/MapsMirrorLayout.svelte
> +  }
There's more clever ways to adjust this CSS, but my thinking was enough values here had to change that explicitly creating new classes is the most legible. Let me know if you disagree!

2022-09-08 21:24 UTC, ebrelsford requested changes

2022-09-08 21:24 UTC, ebrelsford commented on src/components/MapsMirrorLayout.svelte
> +  }
That's fair, I can see how explicit classes is nice in some ways.

When I see a selector like `.map-container-column` I expect it to be a column, so it's confusing when it's not. Renaming it `.column-map-container` or `.mirror-column-map-container` or similar feels a little clearer to me. At that point I wonder if it's worth using more complex selectors (say, `.mirror-column-orientation .map-container`).

What do you think about either renaming these or using nested selectors?

2022-09-09 19:18 UTC, aparlato commented
@ebrelsford good call. I just went ahead and simplified this with nested selectors like you suggest. I also simplified the way we handle borders. This has the side effect that borders between maps are _slightly_ (1px) thicker since the border property doesn't appear to let you draw a border at 0.5px. I tried to mitigate this thickness by using a slightly less harsh color than full black. Let me know if this works for you!

2022-09-09 21:24 UTC, ebrelsford approved these changes

2022-09-09 21:55 UTC, merged